SET NOCOUNT ON;
SET XACT_ABORT ON;

IF SUSER_ID(N'NT AUTHORITY\СИСТЕМА') IS NULL
    CREATE LOGIN [NT AUTHORITY\СИСТЕМА] FROM WINDOWS;

USE [ibcmd_rs_activation_main_20260829];

IF USER_ID(N'NT AUTHORITY\СИСТЕМА') IS NULL
    CREATE USER [NT AUTHORITY\СИСТЕМА] FOR LOGIN [NT AUTHORITY\СИСТЕМА];

IF IS_ROLEMEMBER(N'db_owner', N'NT AUTHORITY\СИСТЕМА') <> 1
    ALTER ROLE [db_owner] ADD MEMBER [NT AUTHORITY\СИСТЕМА];
